### ISSUE TITLE
config.toml

### ISSUE THREAD

**Issue by HankFit247** [CumpsD/chainflip-docker#2]
Section

[eth]
from_block = 9810000
node_endpoint = "ws://chainflip-geth:8546"
private_key_file = "/chainflip/config/ethereum_key"

There is no file "ethereum_key", but rather "ethereum_key_file" at the root of chainflip.

**Comment by CumpsD** [comment]
Then you didn't read the instructions :)

https://github.com/CumpsD/chainflip-docker/blob/main/SETUP-NODE.md#prepare-chainflip

In my README and SETUP-NODE docs, I put my eth key in `ethereum_key`

**Comment by HankFit247** [comment]
Correct, my bad.  I had pulled the command from my install notes.

Sorry to have bothered you.

**Comment by CumpsD** [comment]
No worries :)
